name: devdevil
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_page.png
    - assets/net.png
    - assets/dev.png
    - assets/eye.png
    - assets/eyeOpen.png
    - assets/google.png
    - assets/face.png
    - assets/devve.png
    - assets/streak.png
    - assets/basic.png
    - assets/dsa.png
    - assets/iv.png
    - assets/oops.png
    - assets/data.png
    - assets/bottomNav/home.png
    - assets/bottomNav/invite.png
    - assets/bottomNav/profile.png
    - assets/bottomNav/social.png
    - assets/network.png
    - assets/invete.gif
    - assets/dp.jpg